### ISSUE TITLE
Picture is not showing 

### ISSUE THREAD

**Issue by shirzartenwer** [avinal/Profile-Readme-WakaTime#28]
Hey Avinal,

Thanks for creating this cool project. I just have one question: I copied the link to show the SVG picture and modified it. But it's not showing the image correctly. Can you give me a hint?

**Comment by avinal** [comment]
Hello @shirzartenwer, I see you have closed the issue, is your problem solved or you still need some help. Feel free to ask :)

**Comment by shirzartenwer** [comment]
@avinal Thanks for following up! Yeah, I realized I needed to wait until I get the first image from WakaTime to see if the image is really displaying or not. In the end, it works without a problem.

Thanks for follow up :)
