### ISSUE TITLE
Wakatime stats public and still not showing

### ISSUE THREAD

**Issue by mny0** [avinal/Profile-Readme-WakaTime#34]

**Comment by avinal** [comment]
Hello @prncAzula, I checked your repository. You are using https://github.com/anuraghazra/github-readme-stats project. Also if you are trying to add that stat, it is working and I can see it right now. 
![image](https://user-images.githubusercontent.com/74113200/128225741-a362ed0a-4044-4a13-b564-cc123058657f.png)

Instead, if you are trying to add my project stat in your profile then you need to follow instructions in README in this project. Feel free to ask if you have any doubts.

**Comment by avinal** [comment]
I am closing this issue if you do not have any further queries. Feel free to reopen if needed.
