### ISSUE TITLE
Which repo to add it in?

### ISSUE THREAD

**Issue by crackedpotato007** [avinal/Profile-Readme-WakaTime#38]
Hey so the repo to the url and secret in are going to be the about me repo or the repo where we want the data from?

**Comment by avinal** [comment]
Hey @arnav7633, 
The secret must be in the repo in which you have added this action. The URL of the image can be used anywhere, as you can see the chart in this repo, it is actually produced in my avinal/avinal repo.

**Comment by crackedpotato007** [comment]
Hello!
