### ISSUE TITLE
[Feature] save the pictures / data in the repo

### ISSUE THREAD

**Issue by Alfxjx** [avinal/Profile-Readme-WakaTime#39]
great actions! can I have the historical data or pictures saved in the repo

**Comment by avinal** [comment]
Hi @Alfxjx, 
Thanks, did you mean data for more than 7 days?

**Comment by Alfxjx** [comment]
thank u for respond, what I mean is a data table to record the weekly wakatime data in the repo use this Actions

**Comment by avinal** [comment]
No, as of now, it is not supported, will add something like that soon.
