### ISSUE TITLE
Only one option?

### ISSUE THREAD

**Issue by CodeByAidan** [avinal/Profile-Readme-WakaTime#44]
Hi I was wondering if there is support for any other embeds currently. I am using two on my personal website right now and I want to see if they can update instead of never updating!

![image](https://user-images.githubusercontent.com/67598470/203210014-aa360178-cb8f-4db3-92fb-27c4a2341aa9.png)
(<i>This image shows my two embeds that I made from 4 days ago... </i>) You can see this live example on my website here: https://livxy.github.io/Portfolio/public/index.html

Thanks, 
Aidan

**Comment by avinal** [comment]
Hello @livxy, these embeds work on a different mechanism than my projects, and as far I remember they should update automatically. Right now there is only one type of graph my project produces.

**Comment by CodeByAidan** [comment]
Interesting, well thank you so much! I appreciate the clarification!
